### ISSUE TITLE
:bangbang: Overflowing component.

### ISSUE THREAD

**Issue by jklagrosa** [coral-xyz/apr-ui#32]
![image](https://user-images.githubusercontent.com/104843990/181222882-261148bd-ebb0-4c91-ad5c-3caf719005d1.png)

- I can work with this one.

**Comment by italoacasas** [comment]
Ups, sorry, I saw this issue but did not notice that you said you wanted to work on this one until now. 

This one is resolved already, but if you are interested in contributing, there are other issues like this one https://github.com/coral-xyz/apr-ui/issues/26; that should be fun.
